import numpy as np
lst1=([2,10],[3,11])
lst2=([3,4],[11,24])
npArr1=np.array(lst1)
npArr2=np.array(lst2)
print("2D array 1:\n",npArr1)
print("2D array 2:\n",npArr2)
print("Dimension of array 1 and 2:",npArr1.ndim,npArr2.ndim)
print("Addition of arrays: \n",np.add(npArr1,npArr2))
print("substraction of arrays:\n ",np.subtract(npArr1,npArr2))
print("Multiplication of arrays:\n",np.dot(npArr1,npArr2))
print("trace of the matrix 1:\n",np.trace(npArr1))
print("trace of the matrix 2:\n",np.trace(npArr2))
print("transpose of the matrix 1:\n",np.transpose(npArr1))
print("transpose of the matrix 2:\n",np.transpose(npArr2))
print("determinent of the array 2:\n",np.linalg.det(npArr2))
